# vim: ft=conf
#email = "user@domain.tld"
#facebook = "facebookusername"
github = "loongarch64"
#gitlab = "gitlabusername"
#linkedin = "linkedinusername"
#stackoverflow = "stackoverflowuserid"
#twitter = "twitterusername"
#weibo = "weibousername"
#zhihu = "zhihuusername"
#instagram = "instagramusername"
#quora = "quorausername"
#tumblr = "tumblrusername"
#reddit = "redditusername"
telegram = "loongson_users"
qq = "922566903"
#dockerhub = "dockerhubusername"
#bitbucket = "bitbucketworkspaceid"
